# Generated by Django 4.2.7 on 2025-09-30 20:07

from django.db import migrations, models
import magazine.models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_remove_post_category_remove_post_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=magazine.models.post_image_path),
        ),
    ]
